name: dart_strapi
description: http client for strapi, you can access your models by name or the custom ones using the http client.
version: 1.1.0
homepage: https://github.com/xantiagoma/dart_strapi

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
